<?php
//require_once( "pda/auth.php" );
require_once( "inc/funcs.php" );
ob_clean( );
echo "<!DOCTYPE html>\r\n<html>\r\n  <head>\r\n      <meta http-equiv=\"Content-Type\" content=\"text/html; charset=";
echo MYOA_CHARSET;
echo "\">\r\n      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0\">\r\n      <meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black\" />\r\n      <meta name=\"format-detection\" content=\"telephone=no\" /> \r\n      <title>";
echo _( "≤Èø¥œÍ«È" );
echo "</title>\r\n      <link rel=\"stylesheet\"  href=\"/pda/style/weixinqy.css\" />\r\n      <script src=\"http://cdn.bootcss.com/zepto/1.1.4/zepto.min.js\"></script>\r\n      <script type=\"text/javascript\" src=\"/pda/js/qywechat.js\"></script>\r\n      <script type=\"text/javascript\">\r\n      var WXS = {};\r\n      var C_VER = \"";
echo $_SESSION['C_VER'];
echo "\";\r\n      var P_VER = \"";
echo $P_VER;
echo "\";\r\n      var isIDevice = (/iphone|ipad/gi).test(navigator.appVersion);\r\n      WXS.URI = window.location.protocol + \"//\" + window.location.host;\r\n      WXS.WXState = \"=4a2a0/9yIo3bsB8NzD0KyKtzHK+r5/Ry\";\r\n      (function(){\r\n\r\n          var onBridgeReady = function(){\r\n              \r\n              //“˛≤ÿµÙ”“…œΩ«∞¥≈•∑¿÷π¥´≤•\r\n              WeixinJSBridge.call('hideOptionMenu');\r\n              \r\n              //Õº∆¨œ‡≤·‘§¿¿ƒ£ Ω\r\n              var imgs = [];\r\n              \$(\".read_content .img_wrap img\").each(function(){\r\n                  imgs.push(WeixinJS.addAuthCode(\$(this).attr(\"src\")));  \r\n              });\r\n              \r\n              if(imgs.length > 0)\r\n              {\r\n                  \$(\".read_content .img_wrap\").delegate(\"img\", \"click\", function(){\r\n                      var img_curl = WeixinJS.addAuthCode(\$(this).attr(\"src\"));\r\n                      WeixinJS.imagePreview(imgs, img_curl)\r\n                  });\r\n              }\r\n          };\r\n          \r\n          if(document.addEventListener){\r\n              document.addEventListener('WeixinJSBridgeReady', onBridgeReady, false);\r\n          }else if(document.attachEvent){\r\n              document.attachEvent('WeixinJSBridgeReady'   , onBridgeReady);\r\n              document.attachEvent('onWeixinJSBridgeReady' , onBridgeReady);\r\n          }\r\n\r\n      })();\r\n      \r\n      var Util = {\r\n          preLoadImage: function(obj, url){\r\n\r\n              //Õº∆¨µƒ‘§º”‘ÿ\r\n              var oImg = \$(\".read_content img\");\r\n              oImg.each(function(){\r\n                  \$(this).wrap(\"<div class='img_wrap'></div>\");\r\n                  var obj = \$(this).parent(\".img_wrap\");\r\n                  var url = \$(this).attr(\"src\");\r\n                  var img = new Image();\r\n                  img.src = url;\r\n                  obj.addClass(\"WX_loading\");\r\n                  if(img.complete){ \r\n                      obj.removeClass(\"WX_loading\").empty().append(img);\r\n                      return;\r\n                  }\r\n                  img.onload = function(){\r\n                      obj.removeClass(\"WX_loading\").empty().append(img);\r\n                  };\r\n                  img.onerror = function(){\r\n                      obj.html('";
echo _( "Õº∆¨º”‘ÿ ß∞‹£°" );
echo "');\r\n                      obj.removeClass(\"WX_loading\");\r\n                  };\r\n              });\r\n              return this;\r\n          },\r\n          pageTitle: function(t){\r\n              document.title = t;  \r\n          },\r\n          loadDefaultAvatar: function(o, s){\r\n              o.onerror = function(){\r\n                  o.src =  WXS.URI + \"/static/images/avatar/\" + s + \".png\";\r\n              }\r\n          }\r\n      }\r\n</script>\r\n</head>";
?>
